# Generated by Django 6.0.1 on 2026-01-20 09:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commentlike",
            options={
                "verbose_name": "Like by user",
                "verbose_name_plural": "Comment likes by users",
            },
        ),
        migrations.AlterModelOptions(
            name="postlike",
            options={
                "verbose_name": "Like by user",
                "verbose_name_plural": "Post likes by users",
            },
        ),
        migrations.RemoveConstraint(
            model_name="postlike",
            name="unique_user_post_like",
        ),
        migrations.RenameField(
            model_name="postlike",
            old_name="user",
            new_name="author",
        ),
        migrations.AddConstraint(
            model_name="postlike",
            constraint=models.UniqueConstraint(
                fields=("author", "post"), name="unique_user_post_like"
            ),
        ),
    ]
