# Generated by Django 6.0.1 on 2026-01-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_alter_commentlike_options_alter_postlike_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="postlike",
            name="id",
        ),
        migrations.AddField(
            model_name="postlike",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
