# Generated by Django 6.0.1 on 2026-01-20 10:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_change_postlike_id_to_bigint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(
                validators=[django.core.validators.MaxLengthValidator(10000)]
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(
                max_length=255,
                validators=[django.core.validators.MinLengthValidator(5)],
            ),
        ),
        migrations.AlterField(
            model_name="postcomment",
            name="content",
            field=models.TextField(
                validators=[django.core.validators.MaxLengthValidator(2000)]
            ),
        ),
    ]
