# Generated by Django 6.0.1 on 2026-01-20 10:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="full_name",
            field=models.CharField(
                max_length=100,
                validators=[
                    django.core.validators.MinLengthValidator(2),
                    django.core.validators.RegexValidator(
                        message="Full name can only contain letters, spaces, and hyphens.",
                        regex="^[a-zA-Zа-яА-ЯёЁ\\s-]+$",
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                max_length=32,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(3),
                    django.core.validators.RegexValidator(
                        message="Username must contain only letters, numbers, and underscores.",
                        regex="^[a-zA-Z0-9_]+$",
                    ),
                ],
            ),
        ),
    ]
